using System;
using System.Linq;
using System.Text;
using static MagnumOpus.SourceGeneration.ComponentAnalyzer;

namespace MagnumOpus.SourceGeneration
{
    /// <summary>
    /// Contains templates for generating ChangedTick property code.
    /// This class handles the actual code generation using string templates
    /// and the information gathered by ComponentAnalyzer.
    /// </summary>
    public static class ComponentTemplate
    {
        /// <summary>
        /// Generates a complete partial class/struct with ChangedTick properties.
        /// </summary>
        /// <param name="componentInfo">Information about the component to generate</param>
        /// <returns>Complete C# source code for the partial type</returns>
        public static string GeneratePartialComponent(ComponentInfo componentInfo)
        {
            var sb = new StringBuilder();

            // File header with generation info
            sb.AppendLine(GenerateFileHeader());
            sb.AppendLine();

            // Using statements
            sb.AppendLine(GenerateUsings());
            sb.AppendLine();

            // Namespace declaration
            if (!string.IsNullOrEmpty(componentInfo.Namespace))
            {
                sb.AppendLine($"namespace {componentInfo.Namespace}");
                sb.AppendLine("{");
            }

            // Class/struct declaration
            var indent = string.IsNullOrEmpty(componentInfo.Namespace) ? 0 : 1;
            sb.AppendLine(GenerateTypeDeclaration(componentInfo, indent));
            sb.AppendLine(CodeGenHelpers.Indent(indent) + "{");

            // Generate backing fields
            sb.AppendLine(GenerateBackingFields(componentInfo.TrackedFields, indent + 1));
            sb.AppendLine();

            // Generate properties
            foreach (var field in componentInfo.TrackedFields)
            {
                sb.AppendLine(GenerateProperty(field, componentInfo.Settings, indent + 1));
                sb.AppendLine();
            }

            // Close type declaration
            sb.AppendLine(CodeGenHelpers.Indent(indent) + "}");

            // Close namespace if present
            if (!string.IsNullOrEmpty(componentInfo.Namespace))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        /// <summary>
        /// Generates the file header with auto-generation warning and metadata.
        /// </summary>
        private static string GenerateFileHeader()
        {
            return @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the MagnumOpus ChangedTick Source Generator.
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------";
        }

        /// <summary>
        /// Generates necessary using statements for the generated code.
        /// </summary>
        private static string GenerateUsings()
        {
            return @"using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Numerics;
using MagnumOpus.ECS;
using MagnumOpus.Enums;
using MagnumOpus.Networking.Packets;
#nullable enable";
        }

        /// <summary>
        /// Generates the partial class/struct declaration.
        /// </summary>
        private static string GenerateTypeDeclaration(ComponentInfo componentInfo, int indentLevel)
        {
            var indent = CodeGenHelpers.Indent(indentLevel);
            var typeKeyword = componentInfo.IsStruct ? "struct" : "class";
            
            var comment = CodeGenHelpers.GenerateComment(
                $"Auto-generated partial {typeKeyword} with ChangedTick property tracking.\n" +
                $"Generated for {componentInfo.TrackedFields.Count} tracked field(s).",
                indentLevel);

            return comment + $"{indent}public partial {typeKeyword} {componentInfo.TypeName}";
        }

        /// <summary>
        /// Generates private backing fields for all tracked properties.
        /// </summary>
        private static string GenerateBackingFields(System.Collections.Generic.List<TrackedFieldInfo> trackedFields, int indentLevel)
        {
            var sb = new StringBuilder();
            var indent = CodeGenHelpers.Indent(indentLevel);

            // Only generate backing fields for fields that don't already exist as backing fields
            var fieldsNeedingBackingFields = trackedFields.Where(f => !f.FieldName.StartsWith("_")).ToList();
            
            if (fieldsNeedingBackingFields.Any())
            {
                sb.AppendLine(CodeGenHelpers.GenerateComment("Auto-generated backing fields for tracked properties", indentLevel));

                foreach (var field in fieldsNeedingBackingFields)
                {
                    var initialValue = !string.IsNullOrEmpty(field.InitialValue) ? $" = {field.InitialValue}" : "";
                    sb.AppendLine($"{indent}private {field.TypeName} {field.BackingFieldName}{initialValue};");
                }
            }

            return sb.ToString();
        }

        /// <summary>
        /// Generates a single property with ChangedTick tracking.
        /// </summary>
        private static string GenerateProperty(TrackedFieldInfo fieldInfo, AutoChangedTickSettings globalSettings, int indentLevel)
        {
            var sb = new StringBuilder();
            var indent = CodeGenHelpers.Indent(indentLevel);

            // Property comment
            var syncType = fieldInfo.IsNetworkSynced ? "network-synced" : "ChangedTick";
            var comment = CodeGenHelpers.GenerateComment(
                $"Auto-generated property for {fieldInfo.FieldName} with {syncType} tracking.\n" +
                $"Updates ChangedTick when value changes using {(fieldInfo.Settings.AlwaysUpdate ? "no equality check" : "equality comparison")}." +
                (fieldInfo.IsNetworkSynced ? $"\nNetwork sync type: {fieldInfo.NetworkSyncSettings.MsgType}" : ""),
                indentLevel);

            sb.Append(comment);

            // Property declaration
            sb.AppendLine($"{indent}public {fieldInfo.TypeName} {fieldInfo.PropertyName}");
            sb.AppendLine($"{indent}{{");

            // Getter with inlining
            if (globalSettings.AggressiveInlining)
            {
                sb.AppendLine($"{CodeGenHelpers.Indent(indentLevel + 1)}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
            }
            sb.AppendLine($"{CodeGenHelpers.Indent(indentLevel + 1)}get => {fieldInfo.BackingFieldName};");

            // Setter
            sb.AppendLine($"{CodeGenHelpers.Indent(indentLevel + 1)}set");
            sb.AppendLine($"{CodeGenHelpers.Indent(indentLevel + 1)}{{");

            // Generate setter body (different for network-synced properties)
            if (fieldInfo.IsNetworkSynced)
            {
                sb.Append(GenerateNetworkSyncSetterBody(fieldInfo, globalSettings, indentLevel + 2));
            }
            else
            {
                sb.Append(GenerateSetterBody(fieldInfo, globalSettings, indentLevel + 2));
            }

            sb.AppendLine($"{CodeGenHelpers.Indent(indentLevel + 1)}}}");
            sb.AppendLine($"{indent}}}");

            return sb.ToString();
        }

        /// <summary>
        /// Generates the setter body with appropriate equality checking and ChangedTick updates.
        /// </summary>
        private static string GenerateSetterBody(TrackedFieldInfo fieldInfo, AutoChangedTickSettings globalSettings, int indentLevel)
        {
            var sb = new StringBuilder();
            var indent = CodeGenHelpers.Indent(indentLevel);

            if (fieldInfo.Settings.AlwaysUpdate || !globalSettings.UseEqualityCheck)
            {
                // Always update ChangedTick regardless of value
                sb.AppendLine($"{indent}{fieldInfo.BackingFieldName} = value;");
                sb.AppendLine($"{indent}ChangedTick = {globalSettings.TickSource};");
            }
            else
            {
                // Only update ChangedTick if value actually changed
                string equalityCheck;

                if (!string.IsNullOrEmpty(fieldInfo.Settings.CustomEqualityMethod))
                {
                    // Use custom equality method
                    equalityCheck = $"!{fieldInfo.Settings.CustomEqualityMethod}({fieldInfo.BackingFieldName}, value)";
                }
                else
                {
                    // Use generated equality comparison
                    equalityCheck = CodeGenHelpers.GetEqualityComparison(
                        fieldInfo.FieldType, 
                        fieldInfo.BackingFieldName, 
                        "value");
                }

                sb.AppendLine($"{indent}if ({equalityCheck})");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{CodeGenHelpers.Indent(indentLevel + 1)}{fieldInfo.BackingFieldName} = value;");
                sb.AppendLine($"{CodeGenHelpers.Indent(indentLevel + 1)}ChangedTick = {globalSettings.TickSource};");
                sb.AppendLine($"{indent}}}");
            }

            return sb.ToString();
        }

        /// <summary>
        /// Generates a diagnostic message for components that can't be processed.
        /// Used when components don't meet requirements (missing partial keyword, etc.)
        /// </summary>
        public static string GenerateDiagnosticComment(string componentName, string issue)
        {
            return $@"//------------------------------------------------------------------------------
// ChangedTick Source Generator Warning
//
// Component '{componentName}' could not be processed:
// {issue}
//
// To fix this:
// 1. Ensure the component is declared as 'partial struct' or 'partial class'
// 2. Verify the component has a 'ChangedTick' field of type 'long'
// 3. Mark fields with [Track] attribute that should trigger ChangedTick updates
//------------------------------------------------------------------------------";
        }

        /// <summary>
        /// Generates a simple property without equality checking (for AlwaysUpdate scenarios).
        /// </summary>
        public static string GenerateSimpleProperty(TrackedFieldInfo fieldInfo, AutoChangedTickSettings globalSettings, int indentLevel)
        {
            var sb = new StringBuilder();
            var indent = CodeGenHelpers.Indent(indentLevel);

            sb.AppendLine($"{indent}public {fieldInfo.TypeName} {fieldInfo.PropertyName}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{CodeGenHelpers.Indent(indentLevel + 1)}get => {fieldInfo.BackingFieldName};");
            sb.AppendLine($"{CodeGenHelpers.Indent(indentLevel + 1)}set");
            sb.AppendLine($"{CodeGenHelpers.Indent(indentLevel + 1)}{{");
            sb.AppendLine($"{CodeGenHelpers.Indent(indentLevel + 2)}{fieldInfo.BackingFieldName} = value;");
            sb.AppendLine($"{CodeGenHelpers.Indent(indentLevel + 2)}ChangedTick = {globalSettings.TickSource};");
            sb.AppendLine($"{CodeGenHelpers.Indent(indentLevel + 1)}}}");
            sb.AppendLine($"{indent}}}");

            return sb.ToString();
        }

        /// <summary>
        /// Generates constructor code that properly initializes tracked properties.
        /// This is used when components have constructors with parameters.
        /// </summary>
        public static string GenerateConstructorInitialization(System.Collections.Generic.List<TrackedFieldInfo> trackedFields, int indentLevel)
        {
            var sb = new StringBuilder();
            var indent = CodeGenHelpers.Indent(indentLevel);

            sb.AppendLine(CodeGenHelpers.GenerateComment("Initialize tracked properties to trigger ChangedTick", indentLevel));

            foreach (var field in trackedFields)
            {
                if (!string.IsNullOrEmpty(field.InitialValue))
                {
                    sb.AppendLine($"{indent}{field.PropertyName} = {field.InitialValue};");
                }
            }

            return sb.ToString();
        }

        /// <summary>
        /// Generates helpful documentation for the generated partial class.
        /// </summary>
        public static string GeneratePartialClassDocumentation(ComponentInfo componentInfo)
        {
            var sb = new StringBuilder();

            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Auto-generated partial component with ChangedTick tracking for {componentInfo.TrackedFields.Count} field(s).");
            sb.AppendLine("/// ");
            sb.AppendLine("/// Generated properties:");

            foreach (var field in componentInfo.TrackedFields)
            {
                var updatePolicy = field.Settings.AlwaysUpdate ? "always updates" : "updates on change";
                sb.AppendLine($"/// - {field.PropertyName}: {field.TypeName} ({updatePolicy})");
            }

            sb.AppendLine("/// </summary>");

            return sb.ToString();
        }

        /// <summary>
        /// Generates the setter body for network-synced properties with MsgUserAttrib packet creation.
        /// </summary>
        private static string GenerateNetworkSyncSetterBody(TrackedFieldInfo fieldInfo, AutoChangedTickSettings globalSettings, int indentLevel)
        {
            var sb = new StringBuilder();
            var indent = CodeGenHelpers.Indent(indentLevel);
            var networkSettings = fieldInfo.NetworkSyncSettings!;

            bool useEqualityCheck = networkSettings.UseEqualityCheck && globalSettings.UseEqualityCheck && !fieldInfo.Settings.AlwaysUpdate;

            if (useEqualityCheck)
            {
                // Only update and sync if value actually changed
                string equalityCheck;

                if (!string.IsNullOrEmpty(fieldInfo.Settings.CustomEqualityMethod))
                {
                    // Use custom equality method
                    equalityCheck = $"!{fieldInfo.Settings.CustomEqualityMethod}({fieldInfo.BackingFieldName}, value)";
                }
                else
                {
                    // Use generated equality comparison - invert it for "if changed" logic
                    var baseComparison = CodeGenHelpers.GetEqualityComparison(
                        fieldInfo.FieldType, 
                        fieldInfo.BackingFieldName, 
                        "value");
                    equalityCheck = baseComparison.StartsWith("!") ? baseComparison.Substring(1) : $"!({baseComparison})";
                }

                sb.AppendLine($"{indent}if ({equalityCheck})");
                sb.AppendLine($"{indent}{{");
                
                var innerIndent = CodeGenHelpers.Indent(indentLevel + 1);
                sb.AppendLine($"{innerIndent}{fieldInfo.BackingFieldName} = value;");
                sb.AppendLine($"{innerIndent}ChangedTick = {globalSettings.TickSource};");
                sb.AppendLine($"{innerIndent}var packet = MsgUserAttrib.Create(NTT.Id, (ulong)value, {networkSettings.MsgType});");
                sb.AppendLine($"{innerIndent}NTT.NetSync(ref packet, {networkSettings.Broadcast.ToString().ToLower()});");
                
                sb.AppendLine($"{indent}}}");
            }
            else
            {
                // Always update and sync regardless of value
                sb.AppendLine($"{indent}{fieldInfo.BackingFieldName} = value;");
                sb.AppendLine($"{indent}ChangedTick = {globalSettings.TickSource};");
                sb.AppendLine($"{indent}var packet = MsgUserAttrib.Create(NTT.Id, (ulong)value, {networkSettings.MsgType});");
                sb.AppendLine($"{indent}NTT.NetSync(ref packet, {networkSettings.Broadcast.ToString().ToLower()});");
            }

            return sb.ToString();
        }
    }
}